### ISSUE TITLE
Some questions about how you debugged this extension...

### ISSUE THREAD

**Issue by LisaWang0306** [pbugnion/jupyterlab-sql#105]
We also want to build a jupyterlab extension. I am wondering whether it is necessary to type the command "jupyter labextensions install ..." or "jupyter lab build" every time I want to debug my project (JS code). It costs a few minutes and I want to save those time. Do you know some quicker ways to debug the project? Thanks!!!

**Comment by pbugnion** [comment]
Hi Lisa,

Thanks for asking this here. Unfortunately, I don't really have the bandwidth at present to help write a new extension (it's not really my area of expertise).

I suggest you ask this on JupyterLab.

Best of luck!
