### ISSUE TITLE
Use correct package name in README

### ISSUE THREAD

**Issue by pbugnion** [pbugnion/jupyterlab-sql#119]
The normalized package name is `jupyterlab-sql`, but in the README, we recommend `pip install jupyterlab_sql`.

**Comment by pbugnion** [comment]
The package name is actually `jupyterlab_sql`. Pypi then normalizes it to `jupyterlab-sql` following [PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names).

The Python *module name* is `jupyterlab_sql`, since modules can't contain `-` characters. This means that both:
- `pip install jupyterlab-sql` and `pip install jupyterlab_sql` work.
- Only `jupyter serverextension install jupyterlab_sql` works.

I will therefore keep using `_` for consistency.

**Comment by x83443647629** [comment]
After uninstalling this plug-in, start jupyterlab to report an error "Error loading server extension jupyterlab _ sql ", how to uninstall it clean. 


as following:
Microsoft Windows [版本 10.0.18362.53]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>jupyter lab
[W 20:24:23.592 LabApp] Failed to fetch commands from language server spec finder`bash-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.601 LabApp] Failed to fetch commands from language server spec finder`dockerfile-language-server-nodejs`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.609 LabApp] Failed to fetch commands from language server spec finder`javascript-typescript-langserver`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.644 LabApp] Failed to fetch commands from language server spec finder`unified-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.650 LabApp] Failed to fetch commands from language server spec finder`vscode-css-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.658 LabApp] Failed to fetch commands from language server spec finder`vscode-html-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.665 LabApp] Failed to fetch commands from language server spec finder`vscode-json-languageserver-bin`:
    expected str, bytes or os.PathLike object, not tuple
[W 20:24:23.672 LabApp] Failed to fetch commands from language server spec finder`yaml-language-server`:
    expected str, bytes or os.PathLike object, not tuple
[I 20:24:24.206 LabApp] JupyterLab extension loaded from c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\jupyterlab
[I 20:24:24.207 LabApp] JupyterLab application directory is c:\users\administrator\appdata\local\programs\python\python37\share\jupyter\lab
[W 20:24:24.648 LabApp] Error loading server extension jupyterlab_sql
    Traceback (most recent call last):
      File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\notebook\notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "c:\users\administrator\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab_sql'
