### ISSUE TITLE
Obscure password

### ISSUE THREAD

**Issue by pbugnion** [pbugnion/jupyterlab-sql#30]
When the cursor is not explicitly in the connection string box, the password should be obscured. We could bind to the focus / blur events on the input to mediate this.

**Comment by martintoreilly** [comment]
The [JupyterLab Credential Store](https://towardsdatascience.com/the-jupyterlab-credential-store-9cc3a0b9356) might also be worth considering if it's easy to connect to JupyterLab SQL.

**Comment by pbugnion** [comment]
Ah nice! That looks like a way to protect credentials loaded in notebooks, which is really useful, but a bit different to our use case: the database password is only present in the browser client, so it never leaves the user's computer. It's never stored on the server.

The only concern this should address is people looking at the user's screen and copying the password.

**Comment by martintoreilly** [comment]
Ah, sorry. I hadn't realised that the connection credentials weren't stored with the notebook.

**Comment by pbugnion** [comment]
Addressed by PR #45 , released in version 0.1.4.
