### ISSUE TITLE
SQL query won't execute and/or expand example documentation

### ISSUE THREAD

**Issue by matthewfeickert** [pbugnion/jupyterlab-sql#47]
Hi, first thanks for making this. It is quite cool.

I am having trouble getting the queries to execute, so I am hoping that I am doing something dumb that you can point out to me.

First, I'm on Ubuntu 16.04 with Python 3.6.8

```
$ python --version
Python 3.6.8
$ pip --version
pip 19.0.3 from /usr/lib/python3.6/site-packages/pip (python 3.6)
```

and I've created a virtual environment to try to test this

```
$ python3 -m venv jupyterlab-testing
```

in which I've run the following

```
pip install jupyterlab_sql
pip install mysqlclient # So can have MySQL with SQLAlchemy on Python 3.6
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build
```

As an example on my local machine I'm using the [MySQL example employees database ](https://github.com/datacharmer/test_db) which I've installed

```
git clone git@github.com:datacharmer/test_db.git
cd test_db
mysql < employees.sql
```

I can then launch with `jupyter lab` and navigate to the SQL tab, but then when I enter in the corresponding URL and a valid query and hit `Ctrl+Enter` (like I would execute a Jupyter Notebook cell) nothing happens

![localhost_attempt](https://user-images.githubusercontent.com/5142394/53854569-925dba00-3f8f-11e9-9aad-fd827197eb76.png)

It isn't clear to me how to execute the query as my keyboard commands don't seem to do anything

As a test, I've also made sure that I can actually access the database in Python with SQLAlchemy

```python
>>> from sqlalchemy import create_engine
>>> engine = create_engine('mysql://USERNAME:PASSWORD@localhost:5432/employees)
>>> engine.connect()
<sqlalchemy.engine.base.Connection object at 0x7f96c89692e8>
>>> print(engine.table_names())
['departments', 'dept_emp', 'dept_manager', 'employees', 'salaries', 'titles']
>>> with engine.connect() as con:
...     rs = con.execute('SELECT * FROM employees LIMIT 10')
...     for row in rs:
...             print(row)
... 
(10001, datetime.date(1953, 9, 2), 'Georgi', 'Facello', 'M', datetime.date(1986, 6, 26))
(10002, datetime.date(1964, 6, 2), 'Bezalel', 'Simmel', 'F', datetime.date(1985, 11, 21))
(10003, datetime.date(1959, 12, 3), 'Parto', 'Bamford', 'M', datetime.date(1986, 8, 28))
(10004, datetime.date(1954, 5, 1), 'Chirstian', 'Koblick', 'M', datetime.date(1986, 12, 1))
(10005, datetime.date(1955, 1, 21), 'Kyoichi', 'Maliniak', 'M', datetime.date(1989, 9, 12))
(10006, datetime.date(1953, 4, 20), 'Anneke', 'Preusig', 'F', datetime.date(1989, 6, 2))
(10007, datetime.date(1957, 5, 23), 'Tzvetan', 'Zielinski', 'F', datetime.date(1989, 2, 10))
(10008, datetime.date(1958, 2, 19), 'Saniya', 'Kalloufi', 'M', datetime.date(1994, 9, 15))
(10009, datetime.date(1952, 4, 19), 'Sumant', 'Peac', 'F', datetime.date(1985, 2, 18))
(10010, datetime.date(1963, 6, 1), 'Duangkaew', 'Piveteau', 'F', datetime.date(1989, 8, 24))
```

Any thoughts on what the problem might be?

**Comment by pbugnion** [comment]
Thanks for raising this.

To help understand further what's going on, can you:
- open the browser console and paste the logs here.
- paste the jupyter server logs.

**Comment by matthewfeickert** [comment]
> Did you mean `shift` + `enter` &mdash; this is what people normally use for notebooks.

Ah, no, I did indeed mean that I was using `Ctrl+Enter` as I much prefer it to `Shift+Enter` as it [does not advance you to the next cell automatically like `Shift+Enter` does](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html#Code-cells-allow-you-to-enter-and-run-code). This has just become so ingrained in my fingers that I forgot until you mentioned this that `Shift+Enter` even worked.

This was the issue, and if I now run with `Shift+Enter` things work as expected :+1: 

![working](https://user-images.githubusercontent.com/5142394/53863244-4884cc00-3faf-11e9-8a4f-a713a05f85a7.png)

I'll close this Issue, but if you don't think it a bad idea I'll also open up a doc PR to explicitly add this as I don't think I'm the only one who uses `Ctrl+Enter`. If it would be possible to add in support for both in the future that would be super great too.

Once again, thanks for making this! I'm excited to use it more.

**Comment by pbugnion** [comment]
Ah great. I'm so used to using shift + enter that I didn't think of other use cases.

I've created two issues:
- #48 to support Ctrl + Enter
- #49 for better docs accessibility (Shift + Enter is documented in the readme at the moment, but that's not very easy to access)

**Comment by pbugnion** [comment]
Thanks also for pointing me to the employees database sample data. That's really useful.

**Comment by matthewfeickert** [comment]
@pbugnion Ah that's super fantastic on both accounts! Yeah, you have it so clearly written in the docs but I think my brain just had a strong bias filter on and did `s/Shift/Ctrl/`. The docs are enough as is, but adding a reminder into the application itself is great. :+1:
