### ISSUE TITLE
how to config with the jupyterlab with envs/py36? 

### ISSUE THREAD

**Issue by chaoyue729** [pbugnion/jupyterlab-sql#53]
every time i use jupyter lab it will be in anaconda2' envs

**Comment by pbugnion** [comment]
Can you be more specific about the issue? Is JupyterLab installed in a Python 2 or a Python 3 environment?

**Comment by pbugnion** [comment]
I'm closing this as it's unclear what the question is. Feel free to reopen and add more details.
