### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by radumas** [pbugnion/jupyterlab-sql#57]
I'm on `jupyterlab-sql 0.1.4` with `JupyterLab `0.35.4` with JupyterHub `0.9.4` in Ubuntu 16.04 trying to connect to a remote PostgreSQL instance (9.6, if that matters).

I have `postgres://username:password@host.ip:5432/postgres` and my query is `SELECT 1;` and I have a spinny wheel next to the connection string.

The Firefox console gives:

```
serverconnection.js:192 POST https://server.ip/jupyter/user/USERNAME/jupyterlab-sql/query?1552318333029 404 (Not Found)
handleRequest @ serverconnection.js:192
makeRequest @ serverconnection.js:75
(anonymous) @ api.js:23
(anonymous) @ api.js:7
push.ScrF.__awaiter @ api.js:3
getForQuery @ api.js:17
(anonymous) @ widget.js:64
(anonymous) @ widget.js:7
push.eeTp.__awaiter @ widget.js:3
updateGrid @ widget.js:60
JupyterLabSqlWidget.editor.execute.connect @ widget.js:38
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
Editor._widget.executeCurrent.connect @ editor.js:16
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_onKeydown @ editor.js:48
EditorWidget.editor.addKeydownHandler @ editor.js:40
algorithm_1.ArrayExt.findFirstIndex.handler @ editor.js:113
findFirstIndex @ array.js:237
CodeMirrorEditor.codemirror_1.default.on @ editor.js:112
signal @ codemirror.js:1166
signalDOMEvent @ codemirror.js:1175
onKeyDown @ codemirror.js:7155
(anonymous) @ codemirror.js:3884
widget.js:5 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 1
Promise rejected (async)
step @ widget.js:6
(anonymous) @ widget.js:7
push.eeTp.__awaiter @ widget.js:3
updateGrid @ widget.js:60
JupyterLabSqlWidget.editor.execute.connect @ widget.js:38
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
Editor._widget.executeCurrent.connect @ editor.js:16
invokeSlot @ index.js:475
emit @ index.js:433
push.qUp9.Signal.emit @ index.js:106
_onKeydown @ editor.js:48
EditorWidget.editor.addKeydownHandler @ editor.js:40
algorithm_1.ArrayExt.findFirstIndex.handler @ editor.js:113
findFirstIndex @ array.js:237
CodeMirrorEditor.codemirror_1.default.on @ editor.js:112
signal @ codemirror.js:1166
signalDOMEvent @ codemirror.js:1175
onKeyDown @ codemirror.js:7155
(anonymous) @ codemirror.js:3884
```

What else would be helpful to post for debugging? `jupyterhub -f config.py --debug` just gives the same 404 AFAICT.

**Comment by pbugnion** [comment]
Have you enabled the server extension? Not sure how you'd do that for JupyterHub, but this is the error I'd expect to see if only the JavaScript extension was enabled.

In a normal lab install (rather than on JupyterHub), you can enable the server extension with:

```
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
```

**Comment by radumas** [comment]
I'm... puzzled by how I installed this. I thought that's what I did...

I'll report back after further investigation.

**Comment by pbugnion** [comment]
You can use `jupyter serverextension list` to get a list of server extensions currently active. It should look like this:

<img width="644" alt="Screenshot 2019-03-14 at 21 18 50" src="https://user-images.githubusercontent.com/1392879/54392172-da22c680-469e-11e9-8335-4a375d1c39d5.png">

**Comment by pbugnion** [comment]
This was almost certainly caused by a missing server extension. There is now a better error message.
