### ISSUE TITLE
Database objects explorer

### ISSUE THREAD

**Issue by rd5802** [pbugnion/jupyterlab-sql#59]
Do you plan to implement database objects explorer (like File explorer) alike database IDE’s have?

**Comment by pbugnion** [comment]
Yes. If anyone is interested in implementing this, shout out here and we can talk about designs.

**Comment by pbugnion** [comment]
This is in progress in PR #67.

**Comment by pbugnion** [comment]
A preliminary database explorer is available following PRs #67 and #104 . As this codebase develops, we can add richer views (e.g. view data types etc.).
