### ISSUE TITLE
Connecting to Database

### ISSUE THREAD

**Issue by DrGiraffe** [pbugnion/jupyterlab-sql#69]
I apologize as this seems rather simple, but do you have an example of connecting to a database? I cannon seem to get this to run after install. 
I am using this format: 
engine = create_engine('mssql+pymssql://scott:tiger@hostname:port/dbname')

I am not sure where to put the statement. Could you please advise?

**Comment by pbugnion** [comment]
Thanks for raising this.

After installing jupyterlab-sql, you should see a new SQL button in the JupyterLab launcher. If you click on this, you will see a textbox with an example connection URL. Just replace that with your URL and it should just work.
