### ISSUE TITLE
Draft7Validator

### ISSUE THREAD

**Issue by sockfish** [pbugnion/jupyterlab-sql#82]
When I run 
jupyter serverextension enable jupyterlab_sql --py --sys-prefix

I get the following error:
ImportError: cannot import name 'Draft7Validator' from 'jsonschema' (/usr/lib/python3/dist-packages/jsonschema/__init__.py)

This is with jupyter 4.4.0, python 3.7.3

**Comment by sockfish** [comment]
Sorry I got this to work by pip3 install --upgrade jsonschema

**Comment by pbugnion** [comment]
Ah thanks -- it sounds like I'm missing a lower bound on the `jsonschema` dependency.

**Comment by pbugnion** [comment]
Resolved in PR #83.
