### ISSUE TITLE
Unable to run commands on console, notebook or SQL launcher 

### ISSUE THREAD

**Issue by LuisFRoch** [pbugnion/jupyterlab-sql#85]
Hi!

I've trying to query my DB while connected without success. I've tried simple queries but in some instances i get a 'SyntaxError: invalid syntax', 'java.lang.RuntimeException: No datasource', 'NameError: name 'Select' is not defined' and when using the SQL window the command doesn't execute. Any ideas how i can solve this issue?

Many thanks!

<img width="612" alt="Screen Shot 2019-06-25 at 10 27 16 AM" src="https://user-images.githubusercontent.com/29665541/60082590-56b05100-9734-11e9-9984-f53038827473.png">

<img width="612" alt="Screen Shot 2019-06-25 at 10 31 57 AM" src="https://user-images.githubusercontent.com/29665541/60082670-80697800-9734-11e9-9131-5c9e76f47401.png">

<img width="612" alt="Screen Shot 2019-06-25 at 10 32 39 AM" src="https://user-images.githubusercontent.com/29665541/60082715-95460b80-9734-11e9-9b3a-38b1560d7e11.png">

**Comment by pbugnion** [comment]
This doesn't add a tab in the notebook -- you should always just use the SQL window.

> SQL window the command doesn't execute

What do you actually see?

**Comment by LuisFRoch** [comment]
> You shouldn't be running the SQL commands in the notebook -- you should always just use the SQL window.
> 
> > SQL window the command doesn't execute
> 
> What do you actually see?

I used commands in the notebook bc that's how i've ran queries in the past; e.g. you create a connector, cursor, fetcher, etc., so i thought since the SQL window doesn't execute the query, i thought the notebook with the SQL kernel would do.

This is what i see, but i can't execute the query. I've gone through sqlalchemy instructions, but it hasn't made any difference.

<img width="1395" alt="Screen Shot 2019-06-26 at 9 27 33 AM" src="https://user-images.githubusercontent.com/29665541/60160002-b53d0400-97f4-11e9-86be-dc27d051f78a.png">

**Comment by pbugnion** [comment]
> I used commands in the notebook bc that's how i've ran queries in the past; e.g. you create a connector, cursor, fetcher, etc., so i thought since the SQL window doesn't execute the query

You can carry on doing this completely independently of jupyterlab-sql. That should just work.

> i can't execute the query

What happens when you press `shift-enter` to in the editor with your SQL command?

**Comment by LuiSRoch** [comment]
> > I used commands in the notebook bc that's how i've ran queries in the past; e.g. you create a connector, cursor, fetcher, etc., so i thought since the SQL window doesn't execute the query
> 
> You can carry on doing this completely independently of jupyterlab-sql. That should just work (whether you have jupyterlab-sql or not). The only think jupyterlab-sql adds is that launcher button and the SQL window you see after that.
> 
> > i can't execute the query
> 
> What happens when you press `shift-enter` to in the editor with your SQL command?
>      Nothing happens.
> Separately, you are still running jupyterlab-sql 0.1.x. How did you install it?
        using the following sometime ago: 
                 pip install jupyterlab_sql
                 jupyter serverextension enable jupyterlab_sql --py --sys-prefix
                 jupyter lab build

**Comment by pbugnion** [comment]
Can you find out what version you are running by running the following command?

```
pip list | grep jupyterlab_sql
```

**Comment by LuiSRoch** [comment]
> Can you find out what version you are running by running the following command?
> 
> ```
> pip list | grep jupyterlab_sql
> ```
I have: jupyterlab-sql                     0.1.8

**Comment by pbugnion** [comment]
Closing as this refers to a very outdated *jupyterlab-sql*. Feel free to re-open if this is still an issue in 0.3.3.
