### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by abetkin** [pbugnion/jupyterlab-sql#86]
This happens when I try to install in a virtualenv (via pipenv or conda)

![jupyterlab_sql](https://user-images.githubusercontent.com/2223279/60089091-781b3800-9748-11e9-8b57-0a29474cede8.png)

Btw, when installing globally, the extension builds ok, but is not loaded when jupyterlab starts

**Comment by CptanPanic** [comment]
I did run as root on my ubuntu server, and everything looks good. But when I restart jupyterlab, I don't see it in the launcher options. I am on jupyterlab 0.35.6  Thanks.

```
"pip install jupyterlab_sql
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build"

```
And I do see : 
```
jupyter serverextension list
config dir: /usr/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 0.35.6 OK
    jupyterlab_sql  enabled 
    - Validating...
      jupyterlab_sql  OK
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 0.35.6 OK
```

**Comment by pbugnion** [comment]
You should be able to either install in a virtual environment that also contains Jupyter, or globally. I'd definitely recommend installing in a virtual environment.

What happens when you try to run the installation commands in a virtual environment?

**Comment by pbugnion** [comment]
Closing this for now. Feel free to re-open if the issue persists.
