### ISSUE TITLE
I followed install instructions, but doesn't show up in launcher

### ISSUE THREAD

**Issue by CptanPanic** [pbugnion/jupyterlab-sql#87]
I did run as root on my ubuntu server, and everything looks good. But when I restart jupyterlab, I don't see it in the launcher options. I am on jupyterlab 0.35.6  Thanks.

```
"pip install jupyterlab_sql
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build"

```
And I do see : 
```
jupyter serverextension list
config dir: /usr/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 0.35.6 OK
    jupyterlab_sql  enabled 
    - Validating...
      jupyterlab_sql  OK
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 0.35.6 OK
```

**Comment by carlosfmedina** [comment]
+1

**Comment by pbugnion** [comment]
What is the output of `jupyter labextension list`?

**Comment by CptanPanic** [comment]
> What is the output of `jupyter labextension list`?
Yes SQL does not show up in that list.

``JupyterLab v0.35.6
Known labextensions:
   app dir: /usr/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.33.1  enabled   X
        @jupyterlab/plotly-extension v0.11.0  enabled   X

   The following extension are outdated:
        @jupyter-widgets/jupyterlab-manager
        @jupyterlab/plotly-extension

   Consider running "jupyter labextension update --all" to check for updates.

**Comment by pbugnion** [comment]
Hmm ... `jupyterlab-sql` should show up on this. What is the output of the following command:

```
python -c "import sys, jupyterlab_sql ; print(jupyterlab_sql.__file__) ; print(sys.exec_prefix)"
```

**Comment by cassioiks** [comment]
I also get this issue. Everything installed and built successfully, but doesn't show up in the launcher.
The extension is showing up when I run the command `jupyter labextension list`:

'''
JupyterLab v1.0.1
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        jupyterlab-sql v0.2.2  enabled  OK
'''

**Comment by pbugnion** [comment]
@cassioiks Thanks for raising this. Jupyterlab-sql 0.2.2 is not compatible with JupyterLab 1.x. Progress on this is tracked in #88 .

**Comment by pbugnion** [comment]
Closing as this refers to an outdated jupyterlab-sql and jupyterlab. Feel free to re-open if the issue persists.

**Comment by Lisalin5813010** [comment]
have the same issue, I installed jupyterlab-sql and build it successfully, but it does not on my launcher.
I did not find any solution here...
My jupyter-lab version is 3.1.0
