### ISSUE TITLE
SECURITY: Spoof package on NPM

### ISSUE THREAD

**Issue by pbugnion** [pbugnion/jupyterlab-sql#89]
It looks like a spoof version of this is available on NPM: https://www.npmjs.com/package/jupyterlab-sql

I don't know what is in that package, but you should definitely not install it. Always install jupyterlab-sql from Pypi.

If you have installed it, I strongly recommend wiping your JLab environment.

**Comment by pbugnion** [comment]
x-ref: https://github.com/quigleyj97/jupyterlab-spreadsheet/issues/12

**Comment by stonebig** [comment]
how do we wipe it out ?

**Comment by pbugnion** [comment]
For reference, at first glance, the package looks like it's just a clone. There is no obvious malicious code in there.

I've submitted a support request to NPM to have it taken down.

**Comment by dhirschfeld** [comment]
Quoting from a [recent npm security bulletin](https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm):

> *The attack was carried out by using a pattern that is becoming more and more popular; publishing a “useful” package (electron-native-notify) to npm, waiting until it was in use by the target, and then updating it to include a malicious payload*

Copying a package and trying to pass it off as authentic isn't kosher and opens up jupyter users to exactly this type of attack.

**Comment by pbugnion** [comment]
NPM have replied with steps to follow -- to avoid having multiple versions of this conversation, I will carry on posting on [this issue on jupyterlab-spreadsheet](quigleyj97/jupyterlab-spreadsheet#12).

**Comment by stonebig** [comment]
any progress on this ?

**Comment by pbugnion** [comment]
Ownership of the package has now been transferred to me, which is great. I can't take it down directly, but I have raised another support request with NPM to do this.

**Comment by stonebig** [comment]
great, waiting for final green  light

**Comment by pbugnion** [comment]
The package is now completely gone. Running:

```
jupyter labextension install jupyterlab-sql
```

... no longer works. Hopefully this will force people to install the package via pip.

**Comment by pbugnion** [comment]
Closing this for now. If anybody thinks there are outstanding problems, feel free to re-open.
