### ISSUE TITLE
ImportError: cannot import name 'Draft7Validator'

### ISSUE THREAD

**Issue by ozaparth2803** [pbugnion/jupyterlab-sql#96]
When I run - ```jupyter serverextension enable jupyterlab_sql --py --sys-prefix```
It says ```ImportError: cannot import name 'Draft7Validator```.
As suggested in one of the issues, I also tried - ```pip install --upgrade jsonschema```. But it says `Requirement already satisfied`.

Can someone help me with this?

**Comment by pbugnion** [comment]
Are Jupyter and jupyterlab-sql in different virtual environments? Does your pip command apply to the virtual environment that jupyterlab-sql is in?

**Comment by ozaparth2803** [comment]
Yes. I installed everything in the same environment.

**Comment by pbugnion** [comment]
Hopefully addressed by PR #106. I'll make a new release with this in a few days.
