### ISSUE TITLE
Allow custom query construction and table browsing simultaneously

### ISSUE THREAD

**Issue by zaneselvans** [pbugnion/jupyterlab-sql#97]
In an unfamiliar database, it would be nice to be able to browse around in the various tables looking at samples of the data while constructing a custom query (i.e. on the same page) so that you can see what all the column names, table names, and values look like, without having to navigate away from the query that you're building. Being able to submit the query, and then continue browsing around as you refine it and re-submit would also be helpful, allowing easy iterative improvement and/or increasingly complex query construction.

**Comment by pbugnion** [comment]
Thanks for raising this. There is nothing stopping you from having multiple panes of `jupyterlab-sql` open at the same time:

<img width="1438" alt="Screenshot 2019-08-11 at 13 10 14" src="https://user-images.githubusercontent.com/1392879/62833594-64189080-bc39-11e9-98e1-faba42b1e4c1.png">


Is that what you''re after?

**Comment by zaneselvans** [comment]
Yes, I guess that's what I'm after. Certainly good enough not to need something specific to this plugin.  Thanks!
